spring:
  datasource:
    ### 数据源
    autoDataSource: enable
    ### 监控
    monitor:
      enable: false
    ### mybatis自动配置
    mybatis:
      enable: enable
    url: xx
    username: xx
    password: xx
    dynamicDataSource:
      read:
        url: xx
        username: xx
        password: xx
      write:
        url: xx
        username: xx
        password: xx
  redis:
    host: xx
    password: xx
    port: 1

